export const DEFAULT_LOCAL_APPLICATION_PUBLIC_HTTP_URL = "http://127.0.0.1:18079";
export const DEFAULT_LOCAL_APPLICATION_PUBLIC_WEBSOCKET_URL = "ws://127.0.0.1:18079";

export const VITE_SDKWORK_IM_H5_APPLICATION_PUBLIC_HTTP_URL =
  "VITE_SDKWORK_IM_H5_APPLICATION_PUBLIC_HTTP_URL";
export const VITE_SDKWORK_IM_H5_APPLICATION_PUBLIC_WEBSOCKET_URL =
  "VITE_SDKWORK_IM_H5_APPLICATION_PUBLIC_WEBSOCKET_URL";
export const VITE_SDKWORK_IM_APPLICATION_PUBLIC_HTTP_URL =
  "VITE_SDKWORK_IM_APPLICATION_PUBLIC_HTTP_URL";
export const VITE_SDKWORK_IM_APPLICATION_PUBLIC_WEBSOCKET_URL =
  "VITE_SDKWORK_IM_APPLICATION_PUBLIC_WEBSOCKET_URL";
export const VITE_SDKWORK_IM_PLATFORM_API_GATEWAY_HTTP_URL =
  "VITE_SDKWORK_IM_PLATFORM_API_GATEWAY_HTTP_URL";
