[package]
name = "sdkwork-routes-im-chat-open-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "sdkwork_routes_im_chat_open_api"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
sdkwork_web_contract.workspace = true
sdkwork_web_core.workspace = true
sdkwork_im_web_bootstrap.workspace = true
conversation-runtime = { workspace = true }
