name: sdkwork_im_flutter_mobile_chat
description: SDKWork IM Flutter Mobile Chat capability
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  im_sdk_generated:
    path: ../../../../sdks/sdkwork-im-sdk/sdkwork-im-sdk-flutter/generated/server-openapi
  intl: any
  sdkwork_im_flutter_mobile_commons:
    path: ../sdkwork_im_flutter_mobile_commons
  sdkwork_im_flutter_mobile_core:
    path: ../sdkwork_im_flutter_mobile_core
  sdkwork_im_flutter_mobile_shell:
    path: ../sdkwork_im_flutter_mobile_shell
  shared_preferences: ^2.5.3

flutter:
  generate: true
  uses-material-design: true
