//! Generated API assembly bootstrap for sdkwork-im.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use std::sync::Arc;

pub struct ApiAssembly {
    pub router: Router,
}

pub async fn assemble_api_router() -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_im_audit_backend_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_automation_app_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_calls_open_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_chat_open_api::gateway_mount().await);
    router = router.merge(sdkwork_routes_im_governance_backend_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_knowledgebase_app_api::gateway_mount().await);
    router = router.merge(sdkwork_routes_im_media_app_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_notification_app_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_ops_backend_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_portal_app_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_projection_open_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_realtime_open_api::gateway_mount());
    router = router.merge(sdkwork_routes_im_social_backend_api::gateway_mount(social_runtime));
    router = router.merge(sdkwork_routes_im_social_open_api::gateway_mount(state));
    router = router.merge(sdkwork_routes_im_space_open_api::gateway_mount(state));
    router = router.merge(sdkwork_routes_im_stream_app_api::gateway_mount());
    ApiAssembly { router }
}
