//! Runtime configuration and payload size limit constants for the automation service.

pub(crate) const AUTOMATION_MAX_IN_FLIGHT_REQUESTS_ENV: &str =
    "SDKWORK_IM_AUTOMATION_MAX_IN_FLIGHT_REQUESTS";
pub(crate) const AUTOMATION_MAX_IN_FLIGHT_REQUESTS_DEFAULT: usize = 1_000;
pub(crate) const AUTOMATION_MAX_IN_FLIGHT_REQUESTS_MAX: usize = 20_000;
pub(crate) const AUTOMATION_MAX_REQUEST_BODY_BYTES_ENV: &str =
    "SDKWORK_IM_AUTOMATION_MAX_REQUEST_BODY_BYTES";
pub(crate) const AUTOMATION_MAX_REQUEST_BODY_BYTES_DEFAULT: usize = 5 * 1024 * 1024;
pub(crate) const AUTOMATION_MAX_REQUEST_BODY_BYTES_MAX: usize = 20 * 1024 * 1024;

pub(crate) const AUTOMATION_EXECUTION_MAX_INPUT_PAYLOAD_BYTES: usize = 128 * 1024;
pub(crate) const AUTOMATION_EXECUTION_MAX_EXECUTION_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_EXECUTION_MAX_TRIGGER_TYPE_BYTES: usize = 128;
pub(crate) const AUTOMATION_EXECUTION_MAX_TARGET_KIND_BYTES: usize = 128;
pub(crate) const AUTOMATION_EXECUTION_MAX_TARGET_REF_BYTES: usize = 512;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_STREAM_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_STREAM_TYPE_BYTES: usize = 128;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_CONVERSATION_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_SCHEMA_REF_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_MEMBER_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_RESULT_MESSAGE_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_AGENT_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_AGENT_SESSION_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_RESPONSE_MAX_AGENT_METADATA_BYTES: usize = 64 * 1024;
pub(crate) const AUTOMATION_AGENT_RESPONSE_FRAME_MAX_TYPE_BYTES: usize = 64;
pub(crate) const AUTOMATION_AGENT_RESPONSE_FRAME_MAX_ENCODING_BYTES: usize = 32;
pub(crate) const AUTOMATION_AGENT_RESPONSE_FRAME_MAX_PAYLOAD_BYTES: usize = 256 * 1024;
pub(crate) const AUTOMATION_AGENT_RESPONSE_FRAME_MAX_ATTRIBUTES_BYTES: usize = 64 * 1024;
pub(crate) const AUTOMATION_AGENT_TOOL_CALL_MAX_ID_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_TOOL_CALL_MAX_NAME_BYTES: usize = 256;
pub(crate) const AUTOMATION_AGENT_TOOL_CALL_MAX_ARGUMENTS_PAYLOAD_BYTES: usize = 128 * 1024;
pub(crate) const AUTOMATION_AGENT_TOOL_CALL_MAX_RESULT_PAYLOAD_BYTES: usize = 256 * 1024;

pub(crate) const AUTOMATION_RUNTIME_MAX_EXECUTIONS: usize = 1_024;
pub(crate) const AUTOMATION_RUNTIME_MAX_EXECUTION_BYTES: usize = 64 * 1024 * 1024;
pub(crate) const AUTOMATION_RUNTIME_MAX_AGENT_RESPONSES: usize = 256;
pub(crate) const AUTOMATION_RUNTIME_MAX_AGENT_RESPONSE_BYTES: usize = 64 * 1024 * 1024;
pub(crate) const AUTOMATION_RUNTIME_MAX_FRAMES_PER_RESPONSE: usize = 1_024;
pub(crate) const AUTOMATION_RUNTIME_MAX_FRAME_BYTES_PER_RESPONSE: usize = 16 * 1024 * 1024;
pub(crate) const AUTOMATION_RUNTIME_MAX_TOOL_CALLS: usize = 1_024;
pub(crate) const AUTOMATION_RUNTIME_MAX_TOOL_CALL_BYTES: usize = 64 * 1024 * 1024;
pub(crate) const AUTOMATION_RUNTIME_TERMINAL_TTL_SECONDS: u64 = 15 * 60;

pub(crate) const AUTOMATION_CAPABILITY_PROFILE_ID: &str = "stable-agent";
pub(crate) const AUTOMATION_GUARDRAIL_POLICY_ID: &str = "automation-tool-call-guardrail-v1";
pub(crate) const AUTOMATION_OPERATOR_OVERRIDE_PERMISSION: &str = "automation.operator_override";
pub(crate) const AUTOMATION_EXECUTION_DELIVERY_PROOF_VERSION: &str =
    "automation.execution.delivery-proof.v1";
pub(crate) const AUTOMATION_ENABLED_CAPABILITIES: [&str; 2] = ["agent.response", "agent.tool_call"];
pub(crate) const AUTOMATION_RESTRICTED_TOOL_PREFIXES: [&str; 2] = ["ops.", "admin."];
