use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

use crate::paths;

/// API surface: open-api
pub const API_SURFACE: &str = "open-api";

pub const ROUTES: &[HttpRoute] = &[
    // Spaces
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACES,
        "space",
        "space.spaces.create",
    ),
    HttpRoute::api_key_or_dual_token(HttpMethod::Get, paths::SPACES, "space", "space.spaces.list"),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE,
        "space",
        "space.spaces.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::SPACE,
        "space",
        "space.spaces.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE,
        "space",
        "space.spaces.delete",
    ),
    // Space members
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_MEMBERS,
        "space",
        "space.members.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_MEMBERS,
        "space",
        "space.members.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_MEMBER,
        "space",
        "space.members.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::SPACE_MEMBER,
        "space",
        "space.members.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE_MEMBER,
        "space",
        "space.members.delete",
    ),
    // Groups
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_GROUPS,
        "space",
        "space.groups.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_GROUPS,
        "space",
        "space.groups.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_GROUP,
        "space",
        "space.groups.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::SPACE_GROUP,
        "space",
        "space.groups.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE_GROUP,
        "space",
        "space.groups.delete",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_GROUP_TRANSFER_OWNER,
        "space",
        "space.groups.transferOwner",
    ),
    // Group members
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_GROUP_MEMBERS,
        "space",
        "space.groupMembers.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_GROUP_MEMBERS,
        "space",
        "space.groupMembers.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_GROUP_MEMBER,
        "space",
        "space.groupMembers.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::SPACE_GROUP_MEMBER,
        "space",
        "space.groupMembers.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE_GROUP_MEMBER,
        "space",
        "space.groupMembers.delete",
    ),
    // Channels
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_CHANNELS,
        "space",
        "space.channels.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_CHANNELS,
        "space",
        "space.channels.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_CHANNEL,
        "space",
        "space.channels.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::SPACE_CHANNEL,
        "space",
        "space.channels.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE_CHANNEL,
        "space",
        "space.channels.delete",
    ),
    // Channel access rules
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_CHANNEL_ACCESS_RULES,
        "space",
        "space.channelAccessRules.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_CHANNEL_ACCESS_RULES,
        "space",
        "space.channelAccessRules.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE_CHANNEL_ACCESS_RULE,
        "space",
        "space.channelAccessRules.delete",
    ),
    // Invitations
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_INVITES,
        "space",
        "space.invitations.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_INVITES,
        "space",
        "space.invitations.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_INVITE,
        "space",
        "space.invitations.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE_INVITE,
        "space",
        "space.invitations.revoke",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_INVITE_ACCEPT,
        "space",
        "space.invitations.accept",
    ),
    // Bans
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SPACE_BANS,
        "space",
        "space.bans.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_BANS,
        "space",
        "space.bans.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::SPACE_BAN,
        "space",
        "space.bans.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::SPACE_BAN,
        "space",
        "space.bans.delete",
    ),
];

pub fn route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(ROUTES)
}
