use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

/// API surface: open-api
pub const API_SURFACE: &str = "open-api";

const SOCIAL_OPEN_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/contacts",
        "social",
        "social.contacts.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/users",
        "social",
        "social.users.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/friend_requests",
        "social",
        "social.friendRequests.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/friend_requests",
        "social",
        "social.friendRequests.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/friend_requests/pending/count",
        "social",
        "social.friendRequests.pending.count.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/friend_requests/{friendRequestId}/accept",
        "social",
        "social.friendRequests.accept",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/friend_requests/{friendRequestId}/decline",
        "social",
        "social.friendRequests.decline",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/friend_requests/{friendRequestId}/cancel",
        "social",
        "social.friendRequests.cancel",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/friendships/{friendshipId}/remove",
        "social",
        "social.friendships.remove",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/contacts/tags",
        "social",
        "social.contacts.tags.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/contacts/tags",
        "social",
        "social.contacts.tags.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        "/im/v3/api/social/contacts/tags/{tagId}",
        "social",
        "social.contacts.tags.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        "/im/v3/api/social/contacts/tags/{tagId}",
        "social",
        "social.contacts.tags.delete",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/contacts/{targetUserId}/preferences",
        "social",
        "social.contacts.preferences.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        "/im/v3/api/social/contacts/{targetUserId}/preferences",
        "social",
        "social.contacts.preferences.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/contacts/{targetUserId}/recommendations",
        "social",
        "social.contacts.recommendations.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/friendships",
        "social",
        "social.friendships.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        "/im/v3/api/social/user_blocks",
        "social",
        "social.userBlocks.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/user_blocks",
        "social",
        "social.userBlocks.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        "/im/v3/api/social/user_blocks/{blockId}",
        "social",
        "social.userBlocks.delete",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/direct_chats",
        "social",
        "social.directChats.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/direct_chats/{directChatId}",
        "social",
        "social.directChats.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/users/{userId}/profile",
        "social",
        "social.users.profile.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        "/im/v3/api/social/users/{userId}/profile",
        "social",
        "social.users.profile.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        "/im/v3/api/social/users/{userId}/settings",
        "social",
        "social.users.settings.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        "/im/v3/api/social/users/{userId}/settings",
        "social",
        "social.users.settings.update",
    ),
];

pub fn open_routes() -> Vec<HttpRoute> {
    SOCIAL_OPEN_API_ROUTES.to_vec()
}

pub fn open_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(SOCIAL_OPEN_API_ROUTES)
}
