[package]
name = "sdkwork-im-ccp-codec-cbor"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
ciborium = { path = "../../vendor/ciborium-0.2.2" }
sdkwork-im-ccp-codec = { workspace = true }
sdkwork-im-ccp-core = { workspace = true }
