[package]
name = "sdkwork-routes-im-audit-backend-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true


[lints]
workspace = true
[lib]
name = "sdkwork_routes_im_audit_backend_api"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
sdkwork_web_contract.workspace = true
sdkwork_web_core.workspace = true
sdkwork_im_web_bootstrap.workspace = true
audit-service = { path = "../../services/audit-service" }
