// Generated by docs/sites/scripts/generate-contract-inventories.mjs.
// Do not edit by hand; authored OpenAPI is the contract authority.

import type { ApiSchemaDefinitionMap } from "./schema-types";

export const generatedOpenApiSchemas = {
  "ActivateFriendshipRequest": {
    "fields": [
      {
        "name": "directChatId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "establishedAt",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "eventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "friendshipId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "initiatorUserId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "peerUserId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "AddConversationMemberRequest": {
    "fields": [
      {
        "name": "principalId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "principalKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "role",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "attributes",
        "type": "object",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "AgentToolCall": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "executionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "agentId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "toolCallId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "toolName",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "argumentsPayload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "resultPayload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "state",
        "type": "AgentToolCallState",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "requestedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "completedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "AppendAgentResponseDeltaRequest": {
    "fields": [
      {
        "name": "frameSeq",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "frameType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "schemaRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "encoding",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "payload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "attributes",
        "type": "StringMap",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "AppendStreamFrameRequest": {
    "fields": [
      {
        "name": "payload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "ApplySharedChannelPolicyRequest": {
    "fields": [
      {
        "name": "appliedAt",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "channelId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "connectionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "eventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "historyVisibility",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "policyId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "policyVersion",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "AutomationExecution": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "principalId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "principalKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "executionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "triggerType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "inputPayload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "outputPayload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "state",
        "type": "AutomationExecutionState",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "retryCount",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "requestedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "completedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "failureReason",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "BindExternalMemberLinkRequest": {
    "fields": [
      {
        "name": "connectionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "eventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "externalDisplayName",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "externalMemberId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "linkId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "linkedAt",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "localActorId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "localActorKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "ChangeConversationMemberRoleRequest": {
    "fields": [
      {
        "name": "memberId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "role",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "CompleteAgentResponseRequest": {
    "fields": [
      {
        "name": "frameSeq",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "resultMessageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "CompleteAgentToolCallRequest": {
    "fields": [
      {
        "name": "resultPayload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "ConversationInboxEntry": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "agentHandoff",
        "type": "boolean",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "conversationType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "displayName",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "avatarUrl",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "displaySource",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "peer",
        "type": "ConversationInboxPeerView",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "preferences",
        "type": "ConversationInboxPreferencesView",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "lastActivityAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "lastMessageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "lastSenderId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "messageCount",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "lastMessageSeq",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "lastSummary",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "lastMessageAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "unreadCount",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "ConversationMember": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "memberId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "principalId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "principalKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "role",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "state",
        "type": "MembershipState",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "joinedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "invitedBy",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "removedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "attributes",
        "type": "Record<string, string>",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "ConversationMessageListResponse": {
    "fields": [
      {
        "name": "code",
        "type": "integer (int32)",
        "description": "Allowed values: 0. Default: 0.",
        "required": true
      },
      {
        "name": "data",
        "type": "object",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true,
        "children": [
          {
            "name": "items",
            "type": "ConversationMessageEntry[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true,
            "children": [
              {
                "name": "tenantId",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "conversationId",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "messageId",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "messageSeq",
                "type": "integer (int32)",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "summary",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": false
              },
              {
                "name": "sender",
                "type": "Sender",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "body",
                "type": "MessageBody",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "messageType",
                "type": "MessageType",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "deliveryMode",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "clientMsgId",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": false
              },
              {
                "name": "streamSessionId",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": false
              },
              {
                "name": "rtcSessionId",
                "type": "string",
                "description": "Defined by the authored OpenAPI contract.",
                "required": false
              },
              {
                "name": "occurredAt",
                "type": "string (date-time)",
                "description": "Defined by the authored OpenAPI contract.",
                "required": true
              },
              {
                "name": "committedAt",
                "type": "string (date-time)",
                "description": "Defined by the authored OpenAPI contract.",
                "required": false
              }
            ]
          },
          {
            "name": "pageInfo",
            "type": "PageInfo",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "highWatermark",
            "type": "integer (int32)",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          }
        ]
      },
      {
        "name": "traceId",
        "type": "string (uuid)",
        "description": "Server-owned request correlation id.",
        "required": true
      }
    ]
  },
  "ConversationSummaryView": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "messageCount",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "lastMessageSeq",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "lastSummary",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "lastMessageAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "CreateAgentDialogRequest": {
    "fields": [
      {
        "name": "agentId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "CreateAgentHandoffRequest": {
    "fields": [
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "handoffSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "handoffReason",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "CreateConversationRequest": {
    "fields": [
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "conversationType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "groupName",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "clientRequestKey",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "initializeKnowledgebase",
        "type": "boolean",
        "description": "For group conversations only. When true, requests one Knowledgebase provisioning attempt after the group is durably created. Omitted or false never reserves, provisions, or validates a group Knowledgebase scope. Default: false.",
        "required": false
      },
      {
        "name": "memberUserIds",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "agentAssignments",
        "type": "ConversationAgentAssignment[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false,
        "children": [
          {
            "name": "agentId",
            "type": "string",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "revisionId",
            "type": "string",
            "description": "Defined by the authored OpenAPI contract.",
            "required": false
          }
        ]
      },
      {
        "name": "policyVersion",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "capabilityFlags",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "historyVisibility",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "retentionPolicyRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "CreateConversationResult": {
    "fields": [
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "eventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "requestKey",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "deliveryStatus",
        "type": "string",
        "description": "Allowed values: \"applied\", \"replayed\".",
        "required": false
      },
      {
        "name": "proofVersion",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "knowledgebaseInitialization",
        "type": "string",
        "description": "Present only when initializeKnowledgebase was true. A failed value means group creation succeeded but the optional remote Knowledgebase provisioning attempt did not complete; the group owner can retry from the Knowledgebase action. Allowed values: \"active\", \"provisioning\", \"failed\".",
        "required": false
      }
    ]
  },
  "CreateRoomRequest": {
    "fields": [
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "roomId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "roomKind",
        "type": "string",
        "description": "Allowed values: \"live\", \"chat\", \"game\".",
        "required": true
      }
    ]
  },
  "CreateRtcSessionRequest": {
    "fields": [
      {
        "name": "rtcSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "rtcMode",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "CreateSystemChannelRequest": {
    "fields": [
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "subscriberId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "EditMessageRequest": {
    "fields": [
      {
        "name": "text",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "parts",
        "type": "ContentPart[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "replyTo",
        "type": "MessageReplyReference",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "summary",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "renderHints",
        "type": "object",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "idempotencyKey",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "EnterRoomResponse": {
    "fields": [
      {
        "name": "member",
        "type": "ConversationMember",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "EstablishExternalConnectionRequest": {
    "fields": [
      {
        "name": "connectionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "connectionKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "establishedAt",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "eventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "externalOrgName",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "externalTenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "InviteRtcSessionRequest": {
    "fields": [
      {
        "name": "signalingStreamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "IssueRtcParticipantCredentialRequest": {
    "fields": [
      {
        "name": "participantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "LagListResponse": {
    "fields": [
      {
        "name": "code",
        "type": "integer (int32)",
        "description": "Allowed values: 0. Default: 0.",
        "required": true
      },
      {
        "name": "data",
        "type": "LagPageData",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "traceId",
        "type": "string (uuid)",
        "description": "Server-owned request correlation id.",
        "required": true
      }
    ]
  },
  "MessageMutationResult": {
    "fields": [
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "messageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "messageSeq",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "eventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "MigrateRoutesRequest": {
    "fields": [
      {
        "name": "targetNodeId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "NotificationTask": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "notificationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sourceEventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sourceEventType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "category",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "channel",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "recipientId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "recipientKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "status",
        "type": "NotificationStatus",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "title",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "body",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "payload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "requestedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "dispatchedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "failureReason",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "OpenStreamRequest": {
    "fields": [
      {
        "name": "streamType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "PageInfo": {
    "fields": [
      {
        "name": "mode",
        "type": "string",
        "description": "Allowed values: \"offset\", \"cursor\".",
        "required": true
      },
      {
        "name": "page",
        "type": "integer",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "pageSize",
        "type": "integer",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "totalItems",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "totalPages",
        "type": "integer",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "nextCursor",
        "type": "string | null",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "hasMore",
        "type": "boolean",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "PortalWorkspaceView": {
    "fields": [
      {
        "name": "name",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "slug",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "environment",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "tier",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "region",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "supportPlan",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "seats",
        "type": "PortalInt64Count",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "activeBrands",
        "type": "PortalInt64Count",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "PostMessageRequest": {
    "fields": [
      {
        "name": "text",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "parts",
        "type": "ContentPart[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "replyTo",
        "type": "MessageReplyReference",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "clientMsgId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "summary",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "renderHints",
        "type": "object",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "PostMessageResult": {
    "fields": [
      {
        "name": "messageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "messageSeq",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "eventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "requestKey",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "deliveryStatus",
        "type": "string",
        "description": "Allowed values: \"applied\", \"replayed\".",
        "required": true
      },
      {
        "name": "proofVersion",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "PostRtcSignalRequest": {
    "fields": [
      {
        "name": "signalType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "schemaRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "payload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "signalingStreamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "PresenceHeartbeatRequest": {
    "fields": [
      {
        "name": "deviceId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "ProtocolGovernanceResponse": {
    "fields": [
      {
        "name": "businessPolicyVocabulary",
        "type": "BusinessPolicyVocabularyResponse",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "capabilityProfile",
        "type": "CapabilityProfileResponse",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "effectiveSnapshot",
        "type": "EffectiveProtocolSnapshotResponse",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "killSwitch",
        "type": "KillSwitchResponse",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "quotaProfile",
        "type": "QuotaProfileResponse",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "rolloutPolicy",
        "type": "RolloutPolicyResponse",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sdkCompatibilityBaseline",
        "type": "SdkCompatibilityBaselineResponse",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "ProtocolRegistryResponse": {
    "fields": [
      {
        "name": "bindings",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "codecs",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "compatibilityMatrix",
        "type": "ClientCompatibilityResponse[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true,
        "children": [
          {
            "name": "blockedExperimentalCapabilities",
            "type": "string[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "clientType",
            "type": "string",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "minimumProtocolVersion",
            "type": "string",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "supportedBindings",
            "type": "string[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "supportedCapabilities",
            "type": "string[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "supportedCodecs",
            "type": "string[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          }
        ]
      },
      {
        "name": "protocolVersion",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "schemas",
        "type": "ProtocolSchemaResponse[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true,
        "children": [
          {
            "name": "bindingProtocols",
            "type": "string[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "kind",
            "type": "string",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "requiredCapabilities",
            "type": "string[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "schema",
            "type": "string",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "stage",
            "type": "string",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          },
          {
            "name": "supportedConsumers",
            "type": "string[]",
            "description": "Defined by the authored OpenAPI contract.",
            "required": true
          }
        ]
      }
    ]
  },
  "ProviderBindingCommitResponse": {
    "fields": [
      {
        "name": "value",
        "type": "object",
        "description": "Provider binding mutation result after applying a control-plane policy change.",
        "required": true
      }
    ]
  },
  "ProviderBindingDriftListResponse": {
    "fields": [
      {
        "name": "code",
        "type": "integer (int32)",
        "description": "Allowed values: 0. Default: 0.",
        "required": true
      },
      {
        "name": "data",
        "type": "ProviderBindingDriftPageData",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "traceId",
        "type": "string (uuid)",
        "description": "Server-owned request correlation id.",
        "required": true
      }
    ]
  },
  "ProviderBindingSnapshotListResponse": {
    "fields": [
      {
        "name": "code",
        "type": "integer (int32)",
        "description": "Allowed values: 0. Default: 0.",
        "required": true
      },
      {
        "name": "data",
        "type": "ProviderBindingSnapshotPageData",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "traceId",
        "type": "string (uuid)",
        "description": "Server-owned request correlation id.",
        "required": true
      }
    ]
  },
  "ProviderPolicyRollbackRequest": {
    "fields": [
      {
        "name": "targetVersion",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "ProviderRegistrySnapshotResponse": {
    "fields": [
      {
        "name": "value",
        "type": "object",
        "description": "Provider registry snapshot for the current control-plane view.",
        "required": true
      }
    ]
  },
  "RemoveConversationMemberRequest": {
    "fields": [
      {
        "name": "memberId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "RequestAgentToolCallRequest": {
    "fields": [
      {
        "name": "executionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "toolCallId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "toolName",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "argumentsPayload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "RequestAutomationExecution": {
    "fields": [
      {
        "name": "executionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "triggerType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "inputPayload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "RequestNotification": {
    "fields": [
      {
        "name": "notificationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sourceEventId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sourceEventType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "category",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "channel",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "recipientId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "recipientKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "title",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "body",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "payload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "RoomView": {
    "fields": [
      {
        "name": "roomId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "roomKind",
        "type": "string",
        "description": "Allowed values: \"live\", \"chat\", \"game\".",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "activeMemberCount",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "maxMembers",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "RouteMigrationResult": {
    "fields": [
      {
        "name": "migratedRouteCount",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sourceDrainStatus",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sourceNodeId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sourceRebalanceState",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetDrainStatus",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetNodeId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "targetRebalanceState",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "RouteNodeLifecycle": {
    "fields": [
      {
        "name": "drainStatus",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "nodeId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "ownedRouteCount",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "rebalanceState",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "RtcParticipantCredential": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "rtcSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "participantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "credential",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "expiresAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "RtcSession": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "rtcSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "initiatorId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "initiatorKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "providerPluginId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "providerSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "accessEndpoint",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "providerRegion",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "rtcMode",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "state",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "signalingStreamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "artifactMessageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "startedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "endedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "RtcSessionMutationResponse": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "rtcSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "initiatorId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "initiatorKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "providerPluginId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "providerSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "accessEndpoint",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "providerRegion",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "rtcMode",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "state",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "signalingStreamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "artifactMessageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "startedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "endedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "requestKey",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "deliveryStatus",
        "type": "string",
        "description": "Allowed values: \"applied\", \"replayed\".",
        "required": true
      },
      {
        "name": "proofVersion",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "RtcSignalEvent": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "rtcSessionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "signalSeq",
        "type": "integer (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "rtcMode",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "signalType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "schemaRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "payload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sender",
        "type": "RtcSignalSender",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "signalingStreamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "occurredAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "SdkWorkApiResponse": {
    "fields": [
      {
        "name": "code",
        "type": "integer (int32)",
        "description": "Allowed values: 0. Default: 0.",
        "required": true
      },
      {
        "name": "data",
        "type": "unknown",
        "description": "Operation-specific payload typed per response schema.",
        "required": true
      },
      {
        "name": "traceId",
        "type": "string (uuid)",
        "description": "Server-owned request correlation id.",
        "required": true
      }
    ]
  },
  "SocialSharedChannelSyncDeadLetterTargetedRequeueRequest": {
    "fields": [
      {
        "name": "requestKeys",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "SocialSharedChannelSyncPendingTargetedClaimRequest": {
    "fields": [
      {
        "name": "requestKeys",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "SocialSharedChannelSyncPendingTargetedReleaseRequest": {
    "fields": [
      {
        "name": "requestKeys",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "SocialSharedChannelSyncPendingTargetedTakeoverRequest": {
    "fields": [
      {
        "name": "allowLegacyUntracked",
        "type": "boolean",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "requestKeys",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "SocialSharedChannelSyncTargetedRepublishRequest": {
    "fields": [
      {
        "name": "requestKeys",
        "type": "string[]",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "StartAgentResponseRequest": {
    "fields": [
      {
        "name": "executionId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "streamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "streamType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "conversationId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "schemaRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "memberId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "agent",
        "type": "AgentSubject",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "StreamFrame": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "streamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "streamType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "scopeKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "scopeId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "frameSeq",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "frameType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "schemaRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "encoding",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "payload",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "sender",
        "type": "Sender",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "attributes",
        "type": "StringMap",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "occurredAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "StreamSession": {
    "fields": [
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "streamId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "streamType",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "scopeKind",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "scopeId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "durabilityClass",
        "type": "StreamDurabilityClass",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "orderingScope",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "schemaRef",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "state",
        "type": "StreamSessionState",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "lastFrameSeq",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "lastCheckpointSeq",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "resultMessageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "openedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "closedAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "expiresAt",
        "type": "string (date-time)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "TransferConversationOwnerRequest": {
    "fields": [
      {
        "name": "memberId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "UpdateReadCursorRequest": {
    "fields": [
      {
        "name": "readSeq",
        "type": "integer (int32)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      }
    ]
  },
  "UpdateRtcSessionRequest": {
    "fields": [
      {
        "name": "artifactMessageId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  },
  "UpsertProviderBindingPolicyRequest": {
    "fields": [
      {
        "name": "domain",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "expectedBaseVersion",
        "type": "string (int64)",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      },
      {
        "name": "pluginId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": true
      },
      {
        "name": "tenantId",
        "type": "string",
        "description": "Defined by the authored OpenAPI contract.",
        "required": false
      }
    ]
  }
} satisfies ApiSchemaDefinitionMap;
