[package]
name = "im-app-context"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
axum.workspace = true
sdkwork-im-ccp-core = { workspace = true }
hmac = "0.12.1"
serde_json.workspace = true
sdkwork_web_core.workspace = true
sdkwork_utils_rust.workspace = true
im-adapters-redis-cache = { path = "../../adapters/redis-cache" }
rand.workspace = true
sha2 = "0.10"
tracing.workspace = true

[dev-dependencies]
sdkwork_utils_rust.workspace = true
