[package]
name = "sdkwork-routes-im-knowledgebase-app-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true


[lints]
workspace = true
[lib]
name = "sdkwork_routes_im_knowledgebase_app_api"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
sdkwork_web_contract.workspace = true
sdkwork_web_core.workspace = true
sdkwork_im_web_bootstrap.workspace = true
conversation-runtime.workspace = true
