[package]
name = "im-postgres-realtime-contracts"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-im-contract-control = { workspace = true }
im-domain-core = { path = "../im-domain-core" }
serde_json.workspace = true
