[package]
name = "sdkwork-im-runtime-link"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
sdkwork-im-ccp-binding-tcp = { workspace = true }
sdkwork-im-ccp-binding-udp = { workspace = true }
sdkwork-im-ccp-binding-quic = { workspace = true }
sdkwork-im-ccp-binding-ws = { workspace = true }
sdkwork-im-ccp-registry = { workspace = true }
sdkwork-im-ccp-control = { workspace = true }
sdkwork-im-ccp-core = { workspace = true }
tracing = "0.1.41"

[dev-dependencies]
sdkwork-im-ccp-codec-json = { workspace = true }
