use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

use crate::paths;

/// API surface: open-api
pub const API_SURFACE: &str = "open-api";

pub const ROUTES: &[HttpRoute] = &[
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATIONS,
        "chat",
        "conversations.create",
    ),
    HttpRoute::api_key_or_dual_token(HttpMethod::Get, paths::INBOX, "chat", "inbox.list"),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION,
        "chat",
        "conversations.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_THREADS,
        "chat",
        "conversations.threads.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::DIRECT_CHAT_BINDINGS,
        "chat",
        "conversations.directChats.bindings.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SHARED_CHANNEL_LINKS_SYNC,
        "chat",
        "conversations.sharedChannelLinks.sync",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::AGENT_DIALOGS,
        "chat",
        "conversations.agentDialogs.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::AGENT_HANDOFFS,
        "chat",
        "conversations.agentHandoffs.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::SYSTEM_CHANNELS,
        "chat",
        "conversations.systemChannels.create",
    ),
    HttpRoute::api_key_or_dual_token(HttpMethod::Post, paths::ROOMS, "chat", "rooms.create"),
    HttpRoute::api_key_or_dual_token(HttpMethod::Get, paths::ROOM, "chat", "rooms.retrieve"),
    HttpRoute::api_key_or_dual_token(HttpMethod::Post, paths::ROOM_ENTER, "chat", "rooms.enter"),
    HttpRoute::api_key_or_dual_token(HttpMethod::Post, paths::ROOM_LEAVE, "chat", "rooms.leave"),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_AGENT_HANDOFF,
        "chat",
        "conversations.agentHandoff.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_AGENT_HANDOFF_ACCEPT,
        "chat",
        "conversations.agentHandoff.accept",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_AGENT_HANDOFF_RESOLVE,
        "chat",
        "conversations.agentHandoff.resolve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_AGENT_HANDOFF_CLOSE,
        "chat",
        "conversations.agentHandoff.close",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_MEMBERS,
        "chat",
        "conversations.members.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_MEMBERS_CURRENT,
        "chat",
        "conversations.members.current.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_AGENTS,
        "chat",
        "conversations.agents.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Put,
        paths::CONVERSATION_AGENTS,
        "chat",
        "conversations.agents.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_BINDING,
        "chat",
        "conversations.binding.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_MEMBERS_ADD,
        "chat",
        "conversations.members.add",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_MEMBERS_REMOVE,
        "chat",
        "conversations.members.remove",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_MEMBERS_TRANSFER_OWNER,
        "chat",
        "conversations.members.transferOwner",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_MEMBERS_CHANGE_ROLE,
        "chat",
        "conversations.members.changeRole",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_MEMBERS_LEAVE,
        "chat",
        "conversations.members.leave",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_MEMBERS_ACCEPT_INVITATION,
        "chat",
        "conversations.members.acceptInvitation",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_READ_CURSOR,
        "chat",
        "conversations.readCursor.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::CONVERSATION_READ_CURSOR,
        "chat",
        "conversations.readCursor.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_MEMBER_DIRECTORY,
        "chat",
        "conversations.memberDirectory.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_PINS,
        "chat",
        "conversations.pins.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::MESSAGE_INTERACTION_SUMMARY,
        "chat",
        "conversations.messages.interactionSummary.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_PROFILE,
        "chat",
        "conversations.profile.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::CONVERSATION_PROFILE,
        "chat",
        "conversations.profile.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_PREFERENCES,
        "chat",
        "conversations.preferences.retrieve",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Patch,
        paths::CONVERSATION_PREFERENCES,
        "chat",
        "conversations.preferences.update",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::MESSAGE_EDIT,
        "chat",
        "messages.edit",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::MESSAGE_RECALL,
        "chat",
        "messages.recall",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::MESSAGE_REACTIONS,
        "chat",
        "messages.reactions.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::MESSAGE_REACTIONS_REMOVE,
        "chat",
        "messages.reactions.remove",
    ),
    HttpRoute::api_key_or_dual_token(HttpMethod::Post, paths::MESSAGE_PIN, "chat", "messages.pin"),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::MESSAGE_UNPIN,
        "chat",
        "messages.unpin",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::MESSAGE_SEARCH,
        "chat",
        "messages.search.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::MESSAGE_FAVORITES,
        "chat",
        "messages.favorites.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::MESSAGE_FAVORITE_CREATE,
        "chat",
        "messages.favorites.create",
    )
    .with_idempotent(true),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::MESSAGE_FAVORITE,
        "chat",
        "messages.favorites.delete",
    )
    .with_idempotent(true),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Delete,
        paths::MESSAGE_VISIBILITY,
        "chat",
        "messages.visibility.delete",
    )
    .with_idempotent(true),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Get,
        paths::CONVERSATION_MESSAGES,
        "chat",
        "conversations.messages.list",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_MESSAGES,
        "chat",
        "conversations.messages.create",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::CONVERSATION_SYSTEM_CHANNEL_PUBLISH,
        "chat",
        "conversations.systemChannel.publish",
    ),
    HttpRoute::api_key_or_dual_token(
        HttpMethod::Post,
        paths::ME_WELCOME_ENSURE,
        "chat",
        "chat.me.welcome.ensure",
    ),
];

pub fn route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(ROUTES)
}
