[package]
name = "sdkwork-im-contract-agent"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
sdkwork-im-contract-core = { workspace = true }
im-domain-core = { path = "../im-domain-core" }
im-time = { path = "../im-time" }
serde.workspace = true
