[package]
name = "sdkwork-im-ccp-binding-udp"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
sdkwork-im-ccp-codec = { workspace = true }
sdkwork-im-ccp-core = { workspace = true }

[dev-dependencies]
sdkwork-im-ccp-codec-json = { workspace = true }
