[package]
name = "im-storage-runtime"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-im-contract-core = { workspace = true }
im-storage-contracts = { path = "../im-storage-contracts" }
serde_json.workspace = true
