[package]
name = "sdkwork-api-im-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-im application HTTP plane."

[lib]
name = "sdkwork_api_im_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork_web_core.workspace = true
chrono = "0.4.44"
tracing.workspace = true
serde_json.workspace = true
sdkwork_utils_rust.workspace = true
im-app-context = { path = "../im-app-context" }
im-platform-contracts = { path = "../im-platform-contracts" }
im-domain-core.workspace = true
im-time.workspace = true
sdkwork-im-contract-agent.workspace = true
im-adapters-postgres-journal = { path = "../../adapters/postgres-journal" }
sdkwork_database_config.workspace = true
social-service = { path = "../../services/social-service" }
space-service = { path = "../../services/space-service" }
session-gateway = { path = "../../services/session-gateway" }
audit-service = { path = "../../services/audit-service" }
automation-service = { path = "../../services/automation-service" }
notification-service = { path = "../../services/notification-service" }
ops-service = { path = "../../services/ops-service" }
portal-service = { path = "../../services/portal-service" }
conversation_runtime = { path = "../../services/sdkwork-comms-conversation-service", package = "sdkwork-comms-conversation-service" }
im-adapters-social-postgres = { path = "../../adapters/social-postgres" }
sdkwork_im_database_pool = { workspace = true }
sdkwork_im_service_readiness = { workspace = true }
calls-service = { path = "../../services/im-calls-service" }
sdkwork-agents-runtime-facade.workspace = true
sdkwork-routes-im-audit-backend-api = { workspace = true }
sdkwork-routes-im-automation-app-api = { workspace = true }
sdkwork-routes-im-calls-open-api.workspace = true
sdkwork-routes-im-chat-open-api = { workspace = true }
sdkwork-routes-im-governance-backend-api = { workspace = true }
sdkwork-routes-im-knowledgebase-app-api = { workspace = true }
sdkwork-routes-im-media-app-api = { workspace = true }
sdkwork-routes-im-notification-app-api = { workspace = true }
sdkwork-routes-im-ops-backend-api = { workspace = true }
sdkwork-routes-im-portal-app-api = { workspace = true }
sdkwork-routes-im-realtime-open-api = { workspace = true }
sdkwork-routes-im-social-backend-api = { workspace = true }
sdkwork-routes-im-social-open-api = { workspace = true }
sdkwork-routes-im-space-open-api = { workspace = true }
sdkwork-routes-im-stream-app-api = { workspace = true }

[dev-dependencies]
tower.workspace = true
