name: sdkwork_im_flutter_mobile
description: SDKWork IM Flutter Mobile Application
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: ^6.4.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  sdkwork_im_flutter_mobile_chat:
    path: packages/sdkwork_im_flutter_mobile_chat
  sdkwork_im_flutter_mobile_contacts:
    path: packages/sdkwork_im_flutter_mobile_contacts
  sdkwork_im_flutter_mobile_core:
    path: packages/sdkwork_im_flutter_mobile_core
  sdkwork_im_flutter_mobile_shell:
    path: packages/sdkwork_im_flutter_mobile_shell

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
