[package]
name = "im-adapters-local-disk"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
fs4 = "0.13.1"
im-domain-core = { path = "../../crates/im-domain-core" }
im-platform-contracts = { path = "../../crates/im-platform-contracts" }
im-storage-contracts = { path = "../../crates/im-storage-contracts" }
im-time = { path = "../../crates/im-time" }
serde.workspace = true
serde_json.workspace = true
